### ISSUE TITLE
[DEV] Useful links and notes

### ISSUE THREAD

**Issue by ufna** [PushkinStudio/AppCenter-SDK-UE4#10]
https://github.com/Microsoft/AppCenter-SDK-Android/blob/develop/sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/model/ErrorReport.java

https://github.com/Microsoft/AppCenter-SDK-Apple/blob/develop/SasquatchMac/SasquatchMacObjC/AppCenterDelegateObjC.m

https://github.com/Microsoft/AppCenter-SDK-Apple/blob/d3eb6c942c39be49a6363f28c86f799eb5c1f5c0/AppCenterAnalytics/AppCenterAnalyticsTests/MSAnalyticsTests.m

**Comment by seffyroff** [comment]
Any plans for this to work on PC Builds?

**Comment by ufna** [comment]
@seffyroff , only MacOS is supported by AppCenter, and it's easy to add it into our plugin (same code as iOS, but another libs). But not in our priority (we're working on mobile games mostly). 

Are you looking for MacOS, or you're speaking about Win/Linux?
