### ISSUE TITLE
Crash reports attachments support

### ISSUE THREAD

**Issue by peetonn** [PushkinStudio/AppCenter-SDK-UE4#19]
AppCenter  supports attachments for crash reports -> https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#add-attachments-to-a-crash-report
Looking for ways to implement this in your plugin. Any pointers in the source code would be helpful!

**Comment by ufna** [comment]
Hi @peetonn ,

Unfortunately it's not supported by plugin, and currently plugin is deprecated, so we won't longer support and develop it anymore, as we've swithed to Firebase completely.
